Reusable workflows are not supported in pypi trusted publishing. Revert to token based authentication

diff --git a/.github/workflows/pypi.yml b/.github/workflows/pypi.yml
--- a/.github/workflows/pypi.yml
+++ b/.github/workflows/pypi.yml
@@ -15,6 +15,11 @@ on:
       index:
         description: "The package index, e.g. PyPI or TestPyPI. Defaults to TestPyPI. Be careful when choosing PyPI, because uploads there cannot be deleted"
         type: string
+    secrets:
+      PYPI_TOKEN:
+        description: "Token that enables publishing to PyPI"
+      TEST_PYPI_TOKEN:
+        description: "Token that enables publishing to TestPyPI"
 
 jobs:
   process_inputs:
@@ -23,24 +28,14 @@ jobs:
       - name: Determine package index
         id: determine_index
         run: |
-          if [[ -z "${{ (inputs || github.event.inputs).index }}" ]]; then
-            echo "index=TestPyPI" >> ${GITHUB_OUTPUT}
-            echo "index_url=https://test.pypi.org" >> ${GITHUB_OUTPUT}
+          if [[ -n "${{ (inputs || github.event.inputs).index }}" ]]; then
+            echo "index=${{ (inputs || github.event.inputs).index }}" >> ${GITHUB_OUTPUT}
           else
-            INDEX=${{ (inputs || github.event.inputs).index }}
-            echo "index=${INDEX}" >> ${GITHUB_OUTPUT}
-            if [[ "${INDEX}" == "TestPyPI" ]]; then
-              echo "index_url=https://test.pypi.org" >> ${GITHUB_OUTPUT}
-            elif [[ "${INDEX}" == "PyPI" ]]; then
-              echo "index_url=https://pypi.org" >> ${GITHUB_OUTPUT}
-            else
-              echo "Invalid package index" && exit 1
-            fi
+            echo "index=TestPyPI" >> ${GITHUB_OUTPUT}
           fi
         shell: bash
     outputs:
       index: ${{ steps.determine_index.outputs.index }}
-      index_url: ${{ steps.determine_index.outputs.index_url }}
 
   build_distributions:
     needs: [process_inputs]
@@ -83,13 +78,37 @@ jobs:
   publish:
     needs: [process_inputs, build_distributions]
     runs-on: ubuntu-latest
-    environment: pypi
-    permissions:
-      id-token: write
     steps:
+      - name: Determine package index token
+        id: determine_index_token
+        run: |
+          INDEX=${{ needs.process_inputs.outputs.index }}
+          if [[ "${INDEX}" == "PyPI" ]]; then
+            INDEX_TOKEN=${{ secrets.PYPI_TOKEN }}
+          elif [[ "${INDEX}" == "TestPyPI" ]]; then
+            INDEX_TOKEN=${{ secrets.TEST_PYPI_TOKEN }}
+          else
+            echo "Invalid package index" && exit 1
+          fi
+          if [[ -n "${INDEX_TOKEN}" ]]; then
+            echo "index_token=${INDEX_TOKEN}" >> ${GITHUB_OUTPUT}
+          else
+            echo "Missing package index token" && exit 1
+          fi
+      - name: Determine package index repository url
+        id: determine_index_repository_url
+        run: |
+          INDEX=${{ needs.process_inputs.outputs.index }}
+          if [[ "${INDEX}" == "PyPI" ]]; then
+            echo "index_repository_url=" >> ${GITHUB_OUTPUT}
+          elif [[ "${INDEX}" == "TestPyPI" ]]; then
+            echo "index_repository_url=https://test.pypi.org/legacy/" >> ${GITHUB_OUTPUT}
+          else
+            echo "Invalid package index" && exit 1
+          fi
       - name: Report version and index which will be used
         run: |
-          echo "Publishing version ${{ needs.build_distributions.outputs.version }} on ${{ needs.process_inputs.outputs.index }} (index URL: ${{ needs.process_inputs.outputs.index_url }})."
+          echo "Publishing version ${{ needs.build_distributions.outputs.version }} on ${{ needs.process_inputs.outputs.index }} (index repository URL: ${{ steps.determine_index_repository_url.outputs.index_repository_url }})."
       - name: Download distributions from artifacts
         uses: actions/download-artifact@v3
         with:
@@ -98,7 +117,8 @@ jobs:
       - name: Publish package distributions
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
-          repository-url: ${{ needs.process_inputs.outputs.index_url }}/legacy/
+          password: ${{ steps.determine_index_token.outputs.index_token }}
+          repository-url: ${{ steps.determine_index_repository_url.outputs.index_repository_url }}
 
   test:
     needs: [process_inputs, build_distributions, publish]
